### ISSUE TITLE
uibc does not work when gstplayer is called automaticaly from sinkctrl

### ISSUE THREAD

**Issue by fhorinek** [albfan/miraclecast#152]
When I use miracle-sinkctrl with --uibc I can see two gstplayer windows one is black and second correctly displays the device. 
Unfortunately uibc does not work in neither.  
When I kill the gstplayer and create new one with same command line
eg. `sudo uibc-viewer 192.168.49.1 5100 -a -p 1991 -r 720x480` than I get a one window that is working correctly.

**Comment by albfan** [comment]
Luckily enough, this problem was detected before.

https://github.com/albfan/miraclecast/issues/115#issuecomment-256821076

The problem was some devices pass uibc info in a way miraclecast don't parse it correctly. miraclecast do not make further testings about parsed arguments and it can result in a bad execution (showing that two windows)

Check if you are using lastest miraclecast implementation, if you are using it and problem persist, there's something more to be aware of.

Just post here logs following guide on [FAQ](https://github.com/albfan/miraclecast/wiki/FAQ).

Info about your source device is interesting too

**Comment by fhorinek** [comment]
I was using latest implementation. 
The source device was android HTC ONE M8.
I will post the logs as soon as possible.

**Comment by albfan** [comment]
This was fixed in #115. Check resolution there
