### ISSUE TITLE
Ubuntu Xenial: ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:898)

### ISSUE THREAD

**Issue by jschwartzenberg** [albfan/miraclecast#158]
I'm following the steps from the readme on Ubuntu Xenial, but each time I run sudo miracle-wifid, I get:
```
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -13 (manager_dbus_connect() in wifid-dbus.c:898)
```

I've got two WiFi devices, one which supports P2P. It doesn't matter whether I have ran res/kill-wpa.sh or not. I also tried specifying the interface explicitly and having an access point running on it.

Am I doing something wrong or running into a bug?

**Comment by albfan** [comment]
Normally this is because lack of this step:

- copy the dbus policy `res/org.freedesktop.miracle.conf` to `/etc/dbus-1/system.d/`

it is done by install phase either on cmake or autotools. Did you install project? it is done with

    # make install

or you can do manually.

`kill-wpa.sh` was designed for a time when ubuntu didn't use systemd for its services. Compare

https://github.com/albfan/miraclecast/blob/master/res/miracle-utils.sh#L130

and

https://github.com/albfan/miraclecast/blob/master/res/miracle-utils.sh#L141

Based on https://wiki.ubuntu.com/SystemdForUpstartUsers I guess ubuntu and debian are using systemd by default so kill-wpa.sh should check exact version to kill with service or with systemd.

One option is use `lsb_release`
https://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/lsbrelease.html

Something like:

    $ if [ $( lsb_release -r | awk '{print $2}' | cut -d . -f 1 ) -ge 15 ] ; then echo "use systemd"; else echo "use service"; fi

should work

An easy way to detect if wpa_supplicant is the right one for miraclecast is check parent process for it.

Network manager normally shows:

    $ pstree -p -s $(pgrep wpa_supplicant)
    systemd(1)───wpa_supplicant(410)

while wpa_supplicant started by miraclecast shows:

    $ pstree -p -s $(pgrep wpa_supplicant)
    systemd(1)───/usr/bin/termin(933)───bash(941)───sudo(6098)───miracle-wifid(6099)───wpa_supplicant(6100)

If I create a branch, Coul you test script changes on kill-wpa.sh?

**Comment by albfan** [comment]
Please check if that helps to control Network manager. Sadly this is a poorly designed approach. We should fix #98 for a better solution and left those scripts for old distros.

**Comment by albfan** [comment]
PR #135 should help to manage this situation.Please provide feedback

**Comment by jschwartzenberg** [comment]
Apologies for the late reply. Are you sure this would work? I can't use Miraclecast even when I disable NetworkManager for all cards for now..

**Comment by albfan** [comment]
This error should be fixed with that solution.

In general miraclecast works, but traces are needed to solve particular problems. as there's lot of possible combinations, feel free to open new bugs with new problems, we are here to help
