### ISSUE TITLE
Support of OpenRC

### ISSUE THREAD

**Issue by archenroot** [albfan/miraclecast#242]
Hi buddy,

I opened here discussion on Gentoo forum along with the request:
https://forums.gentoo.org/viewtopic.php?p=8139088#8139088

There is some response already about not being it easy task, if you can provide some hints yourself, I think it will help.

I mean I will create package for Gentoo anyway, but this will be limited to SystemD which I myself don't use, but I have no problem with create virtual machine for SystemD ebuild development only..

Thanks again for cooperation or possible help

**Comment by albfan** [comment]
I'm waiting for reply to join to the gentoo forum, meanwhile I think you can start a repo with workflow to package for gentoo and we can collaborate there, sounds good?

**Comment by GavinDarkglider** [comment]
I agree, it would be nice to see this work with OpenRC. Personally dont like SystemD, and would love to have this working with openrc. Ebuilds are fairly easy to write, so if you need help there, I can help you out.

**Comment by albfan** [comment]
@GavinDarkglider feel free to start something and link here. I don't know what an ebuild is

See there's nothing ready without systemd at this time (there's just an unmaintained library for miracast which someone needs to review)

**Comment by GavinDarkglider** [comment]
Ebuilds are like scripts that are used by portage(The package manager in gentoo based distributions) to download, patch, compile, and install packages. They are fairly easy to write, first you define use flags, which are Boolean variables that can be set for each package, to use specific libraries, or enable or disable features. eg, if open rc and systemd are supported, you dont want it building for both, so that would be how you set that. You also tell it what dependencies are required to run, and build. These can be set by use flags as well. then you tell it where to download the source for the version, tell it to apply patches, and then build and install. There is a structure defined for this, but this is the gist of an ebuild. Since I dont use systemd, anything I build will try to install it, or it will fail installation, so it will be impossible for me to test, but I can put together the basics, so you get the idea.

**Comment by albfan** [comment]
Ok, sounds like a PKGBUILD for arch linux. @GavinDarkglider link here a repo (miraclecast-ebuild or similar)

@archenroot  says something about a VM, will be that a qemu?

**Comment by akhuettel** [comment]
Packaging this for gentoo is not so complicated in principle, I'll try over the next days. My only problem is that I dont have systemd... will try to get along with openrc/udev/elogind and see what happens.

**Comment by albfan** [comment]
Will check it and get to you back soon. Everything in master are fixes and improvements, no unstable features. I want to make a release when we don't have to shutdown normal wifi

**Comment by joakim-tjernlund** [comment]
Nice project! need this too, but seems stalled?

**Comment by albfan** [comment]
@akhuettel I squash your openrc branch and looks ok to me. Will add ENABLE_SYSTEMD to meson and autotools and merge.

you will be properly credited.
