### ISSUE TITLE
UIBC mouse input

### ISSUE THREAD

**Issue by eelife** [albfan/miraclecast#267]
Hi alberto, 

This isn't so much an issue as confusion on my part. I have used the --uibc command line option when running miraclecast in startx. A cursor appears in the miraclecast window, but when I click it does not do anything, is this normal operation? Whats the point of uibc? 

Also how can i make the entire picture show across the entire screen, currently the resolution is correct, but the window only takes up a part of the screen i am casting to.

Thanks!

**Comment by albfan** [comment]
Don't know what you mean with startx, neither with cursor.

UIBC means that miraclecast opens a connection with source sending the touches and keyboard press on sink.

For that, when you use `--uibc` option a different player is used (gstplayer instead of miracle-gst) which is listening to keyboard and your clicks on it.

Do that help on your doubt?

**Comment by eelife** [comment]
yes it does!
