### ISSUE TITLE
Support for 4K UHD (2160p)

### ISSUE THREAD

**Issue by corny** [albfan/miraclecast#274]
MiracleCast seems to lack support for resolutions higher than 2K. Which efford has to be made, to add support for 4K UHD with 3840 × 2160 pixels?

**Comment by albfan** [comment]
If you read the spec here https://github.com/albfan/miraclecast/wiki/files/Wi-Fi_Display_Technical_Specification_v2.1_0.pdf (table 71) CEA resolution supports up to 4096x2160 p60

So it only depends on source and sink supporting it. 

As you don't  specify framerate, this is the config for filter output to that resolutions in whatever framerate:

    miracle-sinkctl --res 3E0000,00,00

More details here  https://github.com/albfan/miraclecast/wiki/miracle-sinkctl#detail-of-resolutions-avaliable

>NOTE: Remember, you are saying what you accept as sink, but if source to not provide such resolutions, stream will fail.

That's why miraclecast accepts all resolutions by default, to let source and sink choose. On RTSP https://en.wikipedia.org/wiki/Real_Time_Streaming_Protocol communication, sink tells source the resolutions it accepts, but don't know how source decides what resolution to use, I guess the higher

Give it a try, and close this is that solve your doubt

**Comment by corny** [comment]
Ok, thanks a lot for the quick response.

Do you have any experience with streaming a browser window to a TV and the required bandwidth? I would like to start Chrome browser in a VM and stream the 4K output to a TV. As an alternative I have to attach a small computer like a [ODROID-c2](http://www.hardkernel.com/main/products/prdt_info.php?g_code=G145457216438) to the TV.

**Comment by albfan** [comment]
Stream from whatever depends on your control on whatever. A browser depends on browser API. Chrome implements that but as closed source. You can buy a chromecast and do all for 30 bucks with a TV having HDMI.

Although with ODROID, you only control the sink.

if you want to use miraclecast ast source, see #4

**Comment by corny** [comment]
Ok, anyway using WifiDirect is not accaptable in my setup. I am going to connect a ODROID via HMID that renders the webpage.
