### ISSUE TITLE
Proposal for a video & enabling github discussions

### ISSUE THREAD

**Issue by raghavk92** [albfan/miraclecast#398]
Hi,
If someone could just make a video of building , installing and running miraclecast on any ubuntu machine(18.04,20.04) and show that one display is being miracasted from a miracast device(windows/android phone) onto the display running miraclecast. That will be great for us noobs to know what is going on exactly and what how things are working (on a system where miraclecast is known to work and is working) .This would be useful for people who are trying to install this on different architectures and don't know what the outputs on the system that is working perfectly with miraclecast has. If there is a video already can someone please point me to it. 

Also if possible please enable github discussions on this repo from settings-> options -> there is a button to enable github discussions so that such type of questions don't need to be created as an issue if not needed.

Thanks

**Comment by albfan** [comment]
Learn to build, create a video is great, but out of scope of this project.

As helpful as it will be, it will only cover a small audience. Learn to use your distro, a buildsystem is something you need to learn outside here.

Keep this issue open will cause the false expectation that someone will do that, when the info is already out there on internet.

There's already a gitter chat for miraclecast, but probably you want to ask those questions in cmake forum or in raspberry pi forums

**Comment by raghavk92** [comment]
what about github discussions enablement. Is that a possibility ?. I think that would be very useful. I found now that there is a hitter but github discussions (new feature of github) could be enabled if you feel it is useful.

Thanks

**Comment by albfan** [comment]
there's already a chat for miraclecast

**Comment by raghavk92** [comment]
which is not being used very much. i don't have any problem if you dont enable discussions. Its just nice to have . Its your wish but i think it would be very useful.

**Comment by albfan** [comment]
For whom? That would be another source of communication I have to maintain.

Everything is great, if someone else maintains it.

You want github discussions on miraclecast because I answer you and you want to know how to build miraclecast on raspbian using cmake which is something out of scope for this project that you should learn outside here.

I understand you ask in good faith, but all just sounds as: I got your attention, do this for me. Didn't see any proactive suggestion that benefits the project, just looking for something that benefits you.
