### ISSUE TITLE
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in ../../../src/wifi/wifid-dbus.c:941)

### ISSUE THREAD

**Issue by andyc76** [albfan/miraclecast#401]
Hi,
Thanks for all your work on this project.

I discovered your work whilst researching on how to connect the pi4 (running raspberry pi os) to a wireless projector.

```
pi@raspberrypi:~/Downloads/miraclecast/build $ sudo miracle-wifid --log-level 9
INFO: miracle-wifid - revision 1.0 Dec 30 2020 09:54:07
ERROR: dbus: cannot claim org.freedesktop.miracle.wifi bus-name: -17 (manager_dbus_connect() in ../../../src/wifi/wifid-dbus.c:941)
DEBUG: exiting.. (main() in ../../../src/wifi/wifid.c:625)
```

i have checked and the file exists

```
pi@raspberrypi:~/Downloads/miraclecast/build $ ls /etc/dbus-1/system.d/org.freedesktop.miracle.conf 
/etc/dbus-1/system.d/org.freedesktop.miracle.conf
```

**Comment by albfan** [comment]
`-17` is `EEXIST` error

https://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html

the function returning that is src/wifi/wifid-dbus.c:941:

https://github.com/albfan/miraclecast/blob/master/src/wifi/wifid-dbus.c#L938

From https://www.freedesktop.org/software/systemd/man/sd_bus_request_name.html

-EEXIST
The name has already been acquired by a different peer, and SD_BUS_NAME_REPLACE_EXISTING was not specified or the other peer did not specify SD_BUS_NAME_ALLOW_REPLACEMENT while acquiring the name.

So probably you have other `miracle-wifid` running in background

**Comment by andyc76** [comment]
Hi, thanks for your reply!

It will give me a resource to search for things before posting!

I should have specified the environment i am running.

The Pi4 is already connected to wlan0 (which i am using via ssh) this is probably why i encountered the error above, i have a separate wireless adapter which will provide me with a wlan1.

I'll try it and let you know.

Thanks!

**Comment by albfan** [comment]
No. If you already have a normal wifi running, miraclecast will reuse the `wpa_supplicant` process instead of start the custom one miraclecast needs  and it will not work, but will not show that error.

Just to let you know, I run two instances of miracle-wifid (without stop current normal wifi). First one (left) start but cannot search for wifi direct devices as `wpa_supplicant` process is incorrect, second one (right) fails to create the dbus service `org.freedesktop.miracle.wifi` as it already exists.

![Captura de pantalla de 2021-01-01 12-56-52](https://user-images.githubusercontent.com/220968/103438215-17b86100-4c31-11eb-88f1-09eec6ab3589.png)

**Comment by albfan** [comment]
Will put a meaningful message for this case so it is easy to understand this corner case error
