### ISSUE TITLE
Build on ubuntu 15.04 issues and fixes

### ISSUE THREAD

**Issue by mbernasocchi** [albfan/miraclecast#49]
after using the easy install (https://github.com/albfan/systemd-ubuntu-with-dbus#easy-install) to get all the dependencies, these additional dependencies are needed to build on Ubuntu 15.04:
`sudo apt-get install libsystemd-dev libglib2.0-dev  libreadline-dev`

if with autotools you need also:
`sudo apt-get install dh-autoreconf`

**Comment by albfan** [comment]
see glib2.0 dependency is already present on configure.ac. readline too but by checking header. libsystemd is generated with that project.

About toolchain, getting it may vary from distro to distro. Seems that you are getting autoreconf as it is a dependencie for dh-autoreconf

http://packages.ubuntu.com/utopic/dh-autoreconf

This issue seems to feet better on ubuntu systemd with kdbus project, Thanks to point out anyway.
