### ISSUE TITLE
Yet another miracast receiver for linux, seeking for help

### ISSUE THREAD

**Issue by rtgiskard** [albfan/miraclecast#501]
Hello, I'm implementing yet another miracast receiver for linux, and there is some problem related to the p2p negotiation, would you like to share the experience [here](https://gitlab.gnome.org/GNOME/gnome-network-displays/-/issues/333), it would help a lot.

Sorry for my not being able to share the code at the time, but I personally hope it would be open-source in the nearby future.

**Comment by albfan** [comment]
Cannot enumerate the number of things that are wrong in this issue.

- Ask for help without share the source code
- Ask for undefined help
- Ping to join to other issue to "share experience". Like share what?

Rethink how you expect to waste other's time, more over if you are payed for that.

Basically, you want to reinvent the wheel on NM for no reason (as you plan to coexists with it) For that miraclecat can be your option as it needs to disable NM (because that integration is not implemented)

I'm ok with guide you to do a new implementation of miracast, but the result from that should be that miraclecast gets a wiki on internals or similar.

So I'm closing this. If you need help, think on how to turn your problem into a benefit for the community:

> I'm implementing another miracast receiver, I'm stuck in step X, how miraclecast does it?

That's a goal that has a clear impact into share knowledge, which is part of why miraclecast is open source
