### ISSUE TITLE
Please tag releases, and store build products on GitHub

### ISSUE THREAD

**Issue by DeflateAwning** [albfan/miraclecast#504]
Please tag release versions using GitHub (with release notes), and upload the build products to GitHub

**Comment by albfan** [comment]
A project cannot manage build products for different OS. that's downstream work for packagers and you should ask for that on your OS distro.

About releases, we are still not ready for a new one, so there're no plans for new release

**Comment by DeflateAwning** [comment]
Most projects like this publish build products with releases.

I'm not asking that you add it to an apt repo (that's for packagers, yes). But releasing builds is very, very standard.

**Comment by DeflateAwning** [comment]
Here are some examples of what is extremely common on tagged GitHub releases:
* https://github.com/syncthing/syncthing/releases/tag/v1.27.2
* https://github.com/dbeaver/dbeaver/releases/tag/23.3.2
* https://github.com/tailscale/tailscale/releases/tag/v1.56.1
* https://github.com/openscad/openscad/releases/tag/openscad-2021.01

As you can see, common build targets are:
* amd64 Windows
* Mac
* amd64 Debian
* amd64 AppImage
* amd64 rpm

Many of these projects use a GitHub Actions flow (or a different docker-based build system) to build these releases.

Why are you being so hostile? Is everything okay?

**Comment by albfan** [comment]
Thanks to compare this single man project with those big organizations.

That makes your suggestion even more ridiculous.

I know other org I can compare to: Microsoft. If they can do releases and binaries, how I dare to not do it?

I'm that hostile because you are a moron, asking someone else to do a job that takes a whole organization, and without any evidence of what that brings as benefit to this project.

Your passive-aggresive updates, doesn't make a difference. I'm waiting on your PR with the github actions to do these binary packages on each release to reopen this case mark it as done. (let me guess: at the moment this turns into your job, you don't have time to do it, right? But I should do it because openscad do it!!!

Hope you learn a bit from this interaction, is ok if you have free time to open this hilarious issues. Probably maintainers just close it. I prefer to teach a lesson about open source.

Reply whatever you want, but if you don't update anything about the issue you open (how to achieve that goal) you will demonstrate you are just a kid with spare time to waste, looking to discuss with adults.

Thanks in advance for your contribution to automatize binary package generation on miraclescast!

**Comment by DeflateAwning** [comment]
Okay, I'd actually love to help you setup GitHub Action builds for this project. I think you should be proud to have created something which _is_ comparable to larger projects.

Can we work together if I do that? If you keep up the hostility though, I'm out.

Can you help suggest which targets you think would be most useful to begin with?

Just to name a small single-person project which has excellent releases with builds, Sleek (a todo.txt manager) is great.

**Comment by albfan** [comment]
I told this doesn't seems a goal for me. As not sure what it resolves. Is on you to find what to build, why, what it resolves.

You're so focused on "how we can do this?", that you don't think about "why we should do this?"

You ask for this, but you don't know what to build. You need to understand this issue is the same as:

"migrate to windows"

Funny you call hostility a maintainer spending its time to teach you that your approach to open source is wrong. You ask for solutions without detect a problem "What this binaries will resolve?"

If you don't know where to start is because there's no real need for this.

If just yourself don't need this binaries, why add this to this project.
