### ISSUE TITLE
which wlan usb adaptor to be used?

### ISSUE THREAD

**Issue by bpipi** [albfan/miraclecast#72]
Hi, 
    I want to know which usb wlan usb adaptor miraclecast supports. Can you tell me the usb adaptor names and model number?. So that I can purchase the one.

    One more thing what are the chances of working this miraclecast? **

> Has anybody Wirelessly mirrored the android screen using this Miraclecast?

**

     Please help me with this

    Thanks

**Comment by albfan** [comment]
I can be strictly on these, but I do use miraclecast with realtek usb dongles and nowadays with an atheros card (not usb)

Search issues for word driver (removing open filter) and will find lot information about all kind of drivers and usbs people use.

I just can remember lot of problems on intel drivers (because of it poor support on *nix OS) but I guess that is independent from been usb or card.

Perso ally I would choose any recent atheros usb (mine is 4 years old or more)

**Comment by bpipi** [comment]
Whenever I use Realtek usb dongles, I get nl80211 not found eventhough i have installed nl80211 drivers. But the atheros dongles wont show this problem.

**Comment by albfan** [comment]
So did you run succesfully miraclecast with atheros dongles?

Is good to have hardware feedback so please post here your hardware test to help others or let others to provide feedback on dongles you couldn't get to work.

**Comment by albfan** [comment]
Can this issue be closed? Any further question?

**Comment by pcmerioles609** [comment]
Good day!

Apologies for commenting in a closed issue but I want to ask if there is a way to determine if a certain
Wi-Fi dongle is compatible or not, because I thought at first that `./test-hardware-capabilities.sh` does the job. (probably not)

I am using a Realtek RTL8192CU and at this moment, my Xperia Z cannot locate my archarm Raspberry Pi2 after executing 

`$ miracle-sinkctl`
`> run 3`

I am currently working on your tips as per [https://github.com/albfan/miraclecast/issues/142](url)
but still the same.

Any ideas? Thanks!

**Comment by albfan** [comment]
That script does the job. It's meaning exactly for that
