### ISSUE TITLE
flamewar about issue tracker administration

### ISSUE THREAD

**Issue by vindicatorr** [albfan/miraclecast#81]
Referring to your comment that you deleted from https://github.com/albfan/miraclecast/issues/41#issuecomment-228023783
>I should give a try again to libwfd. Ireference it for #3, thanks.

(https://github.com/albfan/miraclecast/issues/3#issuecomment-228023926)
>>Sometimes you can see the forest for the trees
>>
>>https://www.freedesktop.org/wiki/Software/miracle/libwfd/
>>
>>Let's see what can be reused

which was your response to my comment that is now deleted for some reason.

Your response to my question as to why it was deleted (https://github.com/albfan/miraclecast/issues/41#issuecomment-228598123):
> That's not the question of issue, which indeed has been resolved.
>
>You can open another issue if that improves in some way miraclecast.
>
>Try to focus on precise issues and detailed solutions that's the purpose of an issue tracker

I first thought it may have been deleted because my comment also contained alternative projects, but you, yourself, referenced the one in https://github.com/albfan/miraclecast/issues/3#issuecomment-228023926 and even the wds one in issue https://github.com/albfan/miraclecast/issues/80#issuecomment-216808136. So that couldn't be the reason.
This issue is being opened in order to prevent future comments, that have proven to be helpful, from being deleted by albfan.
Knowing that comments that "may" be useful, may also be deleted, may prevent people from wanting to post at all.

**Comment by albfan** [comment]
I do recommend people to use whatever project which allow him to get miracast functionality. I think wds can be compiled on mac and windows, (miraclecast cannot) so is a great alternative

https://github.com/albfan/miraclecast/issues/80

I wish to drop out heavy systemd kbus funcionality as is a complex prerrequisite for many people preventing them to use miraclecast, but since kdbus is enable by default from version 221, all that deleted comments are simply noise for people wanting to now something about "kdbus not mainlined yet". 

Suppose someone get there from web search because it has an systemd previous to 221 without kdbus. He only want to known how to solve that (upgrading systemd to version 221 or above)

What has to do that with trying wds project or compile a kernel or that you own an intel card? Resolve an issue is a matter of find solutions and get it documented. Delete a comment that mislead the issue objetive is a common task.

I do post a comment to you about open different issues if you want to continue with your test. If you fork libwfd, and get it to work and want to comment on #80 about that, I guess that will help mac or windows people to be able to use miracast.

Understand that recompile a kernel is not an issue related to miraclecast.

You're welcome to open whatever constructive issue. These one seems like a flamewar about delete comments or not. I do like and you don't. I will delete this issue too. I will not explain you this a third time.
